#!/usr/bin/env bash
# A script to Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy
config=\
'
backend nouha-backend
        balance roundrobin
        server 197268-web-01 34.207.188.121 check
        server 197268-web-02 34.224.63.185 check
frontend nouha-frontend
        bind *:80
        mode http
        default_backend nouha-backend
'
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
